# Generated by Django 4.1.7 on 2023-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code of video')),
                ('file', models.FileField(null=True, upload_to='final_videos')),
            ],
        ),
    ]
