# Generated by Django 4.1.7 on 2023-02-24 12:37

from django.db import migrations, models
import generator.models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.CharField(default=generator.models.genetate_unique_code, max_length=8, unique=True, verbose_name='code of video'),
        ),
    ]
